language: java
jdk:
- openjdk11
deploy:
  provider: releases
  api_key:
    secure: keac5ZUBUNiHiw5dPeIv9qDyWKvAZU31L/0+DDqj4052VNTG5gmgDxx/xAWBDx74ToNsNIDXh66CMYmjIVfJaLiodW+cxVTAn4jl9kpZ86f47XsCVD+2Qpk9ObRu48897bzwm9enWwnMuSFu2FYi9Da657CgdSN3owNpAKfC0wPcmdhl9hQScoCqWgQH1dPW6k4W6oy8Vb1F8acI522aDJZ73/eNPkQM5SAhUD627WgVZjp90N50QOLgLFwYjHgkCfhGx57pOord+NQYtf6Ptw5xpS+vjqNADR1LkdKxCbu9STDpi6R0mEJRnPSC9r3sGrCrcGchXv0FRozx8SROGLR8fGAZvkhLyIfjobKLUB7GTPvuFloPGdpvjdtCvyi5+7Q11f7uPCGhZgPeHz40h8SDiwcUvmDLY7EcaqPMP/EzgVDuygp7BSeCkXwX5nv4ty5C++eVAGIM62tiwG8Qz4BYmWDnnJ8H2J3rgoLOTrf++DDYbdM7AfNSFOcCGt+qT7O6HIHMbbISWa9Z8MGF1PTdiLqm2s3M16YZCUrYFbmAAH+m9ERLfhYY9LFbRkHN4Tv8RB/n4g9elBr+OR3jANETP0iRwQctZRGuySloM8ujNuwTavkZ+HiyhUAVnHW6bQZ55+vwcpzcYcGLtlS43kXKEY7p8ewfmqiZ4cJUhvc=
  file: build/distributions/*
  on:
      tags: true
